[theme]
#P2S Inc Blue: 3B6D89
#P2S Eng Teal: 00C496
#P2S Cx Light Blue: 009CCD
#P2S Cm Orange: FB9A2D
#Black: 000000
primaryColor="00C496"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"
